### PR TITLE
update to Zig version 0.11.0-dev.3821+e7f872c9c

### PR DESCRIPTION
**Pull request by BratishkaErik**

### CODE REVIEW

**Comment by BratishkaErik** [comment]
Looks like Zig from CI is not updated yet

**Comment by kooparse** [comment]
thanks, I will merge this soon :)

**Comment by kooparse** [comment]
lgtm!

**Review by kooparse — APPROVED** [review]

**Comment by BratishkaErik** [comment]
Thanks!

**Pull request merged**
