### PR TITLE
New generic vectors, using std.meta.Vector

### PR DESCRIPTION
**Pull request by BratishkaErik**
No more duplication of code! No more a.add(b).sub(c)! Just use a + b - c! More info about vectors you can find at https://ziglang.org/documentation/master/#Vectors

Yep, this is a breaking one. Happy New Year!

### CODE REVIEW

**Comment by kooparse** [comment]
Thanks so much for this incredible PR (and happy new year too!) :-) 

I'm currently adding a commit with a `new` method for all vectors. I trying to have this kind of API: 
```
_ = Vec3.new(3, 4, 5)
```
But it seems impossible to do with the current compiler ability. In order to achieve this, I'm trying that: 

```
   usingnamespace switch (dimensions) {
    2 => extern struct {
        pub usingnamespace Self;

        pub fn new(x: T, y: T) Vector {
           return [2]T{ x, y };
        }
    },
    3 => extern struct {
        pub usingnamespace Self;

        pub fn new(x: T, y: T, z: T) Vector {
            return [3]T{ x, y, z };
        }

        /// Shorthand for (0, 0, -1).
        pub fn back() Vector {
            return [3]T{ 0, 0, -1 };
        }

        /// Shorthand for (0, 0, 1).
        pub fn forward() Vector {
            return [3]T{ 0, 0, 1 };
        }

        /// Construct the cross product (as vector) from two vectors.
        pub fn cross(lhs: Vector, rhs: Vector) Vector {
            return [3]T{
                (lhs[1] * rhs[2]) - (lhs[2] * rhs[1]),
                (lhs[2] * rhs[0]) - (lhs[0] * rhs[2]),
                (lhs[0] * rhs[1]) - (lhs[1] * rhs[0]),
            };
        }
    },
    4 => extern struct {
        pub usingnamespace Self;

        pub fn new(x: T, y: T, z: T, w: T) Vector {
            return [4]T{ x, y, z, w };
        }
    },
    else => Self,
};
```

Of course, the compiler says `error: import of 'new' overrides existing definition`, even if it should works theoretically.

The best version I could make: 

```
/// Construct new vector.
pub fn new(values: [dimensions]T) Vector {
    return values;
}

// Used like that:
_ = Vec3.new(.{1, 2, 3});
```

So if you have any clue for doing this, I'm all ears! :-)

But besides that, lgtm to me, I'll just add some spaces here and there, could you allow me to add new commits to your fork? The checkbox "Allow edits from maintainers." must be checked for that!

**Comment by BratishkaErik** [comment]
> But it seems impossible to do with the current compiler ability. In order to achieve this, I'm trying that:

I did almost as much as you did! But only using ```if```, because I wasn't sure if ```switch``` would work comptime, and I ran into the same error.

I probably should've written whatelse I tried so you don't do extra work

> Vec3.new(.{1, 2, 3});

Is it an anonymous array??? LOL. I thought they weren't in the language, so I made a function that takes anytype (it checks inside to see if it is a ```struct```) and then ```inline for``` goes through all the fields.

But then I thought that since people would have to rewrite all the lines with ```Vec3.new``` anyway, I decided to remove this method and use regular syntax.

**Comment by BratishkaErik** [comment]
> The checkbox "Allow edits from maintainers." must be checked for that!

It is already set

**Comment by BratishkaErik** [comment]
So we have two variants:

```
var vector = Vec3.new(.{1, 2, 3});
```

and

```
const Vector = std.meta.Vector(3, f32)
var vector: Vector = [_]f32{1, 2, 3}
```

In functions from a generic vector it is automatically converted without explicitly specifying the type, but if you use @minimum(vector1, vector2), etc. directly, you have to declare it this way... strange.

I prefer the first option. I'm all for it!

**Comment by BratishkaErik** [comment]
It may be a while before I will be able to login again and continue this. There are protests here in Kazakhstan and the government is slowing down the internet

**Comment by kooparse** [comment]
I added my commit, perfect! :-) 

> Is it an anonymous array??? LOL. I thought they weren't in the language

Yup, it's an array literals (see https://ziglang.org/documentation/0.9.0/#Anonymous-List-Literals). 
So for `Vec3.new(.{1, 2, 3});`, the compiler could infer the type because he knows the function signature with `Vec3`.

> It may be a while before I will be able to login again and continue this. There are protests here in Kazakhstan and the government is slowing down the internet

I just saw that on the news, hope you're fine! Take care :-)

**Comment by kooparse** [comment]
So finally, we have `VectorN.new(x, y, z)` syntax! :)

The main issue was `pub usingnamespace Self` in the nested struct. 
So this works as expected! 
```
        usingnamespace switch (dimensions) {
            2 => extern struct {
                /// Construct new vector.
                pub fn new(x: T, y: T) Vector {
                    return [2]T{x, y};
                }
            },
            3 => extern struct {
                /// Construct new vector.
                pub fn new(x: T, y: T, z: T) Vector {
                    return [3]T{x, y, z};
                }

                /// Shorthand for (0, 0, -1).
                pub fn back() Vector {
                    return [3]T{ 0, 0, -1 };
                }

                /// Shorthand for (0, 0, 1).
                pub fn forward() Vector {
                    return [3]T{ 0, 0, 1 };
                }

                /// Construct the cross product (as vector) from two vectors.
                pub fn cross(lhs: Vector, rhs: Vector) Vector {
                    return [3]T{
                        (lhs[1] * rhs[2]) - (lhs[2] * rhs[1]),
                        (lhs[2] * rhs[0]) - (lhs[0] * rhs[2]),
                        (lhs[0] * rhs[1]) - (lhs[1] * rhs[0]),
                    };
                }
            },
            4 => extern struct {
                /// Construct new vector.
                pub fn new(x: T, y: T, z: T, w: T) Vector {
                    return [4]T{x, y, z, w};
                }
            },
            else => {},
        };
```

**Comment by kooparse** [comment]
Thanks again for this PR! :)

**Comment by kooparse** [comment]
I reverted the PR, my main problem now is the different returned type of a `GenericVector` and functions like `set()`. They're not the same. I need to think a bit more about it :)

**Pull request merged**
