### PR TITLE
Add 'extractAxisAngle' method for quaternion

### PR DESCRIPTION
**Pull request by vvcarvalho**

### CODE REVIEW

**Comment by kooparse** [comment]
Hi! Thanks for your PR! 
I'm asking myself, is this not the same as [extractRoration](https://github.com/kooparse/zalgebra/blob/main/src/quaternion.zig#L237-L254)?

**Comment by vvcarvalho** [comment]
Hey there, so, as an end result they are equivalent. Just a different representation. The reason I needed this function was to interface with the `raylib` C lib.

The differences in the formalism are summarized [here](https://en.wikipedia.org/wiki/Rotation_formalisms_in_three_dimensions#Formalism_alternatives)

**Comment by kooparse** [comment]
After that, I will probably rename the `extractRotation` to `extractEulerAngles`

**Comment by vvcarvalho** [comment]
Absolutely fine with me! Actually makes me remove some code elsewhere in my codebase.

Thanks for the good work :)

**Pull request merged**
